name: Run quality checks on pull requests

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Run linter
        run: yarn lint
      - name: Run tests
        run: yarn test
        env:
          CI: true
